onlyBuiltDependencies:
  - '@fortawesome/fontawesome-common-types'
  - '@fortawesome/free-brands-svg-icons'
  - '@fortawesome/free-solid-svg-icons'
  - '@sveltejs/kit'
  - es5-ext
  - esbuild
  - svelte-preprocess
  - unrs-resolver

overrides:
  cookie@<0.7.0: '>=0.7.0'
  esbuild@<=0.24.2: '>=0.25.0'
  tmp@<=0.2.3: '>=0.2.4'
