import { defineConfig } from '@dovenv/core'
import {
	createBadgeURL,
	createMdLinks,
	joinUrl,
	writeFile,
} from '@dovenv/core/utils'

import pkg         from '../package.json' with { type: 'json' }
import { getMark } from './mark.js'

const createTableRow = ( name, type ) => `| <img src="https://github.com/${name}.png?size=72" alt="${name}" style="border-radius:100%"/> | ${name} |  ${type} | [@${name}](https://github.com/${name}) |`

/**
 * Creates a Markdown link object with a badge image URL.
 *
 * @param   {object} params         - The parameters for creating the link.
 * @param   {string} params.name    - The name to display on the badge.
 * @param   {string} params.url     - The URL to link to.
 * @param   {string} [params.color] - The color of the badge.
 * @param   {string} [params.logo]  - The logo to use on the badge.
 * @returns {object}                - An object containing the name, URL, and badge image URL.
 */
const createMdLink = ( {
	name, url, color = 'black', logo,
} ) => ( {
	name   : name,
	URL    : url,
	imgURL : createBadgeURL( {
		color,
		logoColor : 'white',
		path      : 'badge/' + encodeURIComponent( name + '-' + color ),
		style     : 'for-the-badge',
		logo,
		name,
	} ),
} )
/**
 * Validate package
 *
 * @param {Record<string, any>} obj - Validate object
 */
const validatePkg = obj => {

	for ( const key in obj )
		if ( !obj[key] ) throw new Error( `(package.json).${key} is required` )

}

/**
 *
 * Generate readme.
 *
 * @param   {typeof import('../package.json')} pkg - package.json
 * @returns {Promise<string>}                      Mark string
 */
const setReadme = async pkg => {

	validatePkg( {
		'author.name'          : pkg.author.name,
		'author.url'           : pkg.author.url,
		'version'              : pkg.version,
		'description'          : pkg.description,
		'repository.url'       : pkg.repository.url,
		'funding.url'          : pkg.funding.url,
		'extra.productName'    : pkg.extra.productName,
		'extra.collective.url' : pkg.extra.collective.url,
		'extra.repoPath'       : pkg.extra.repoPath,
	} )

	const licensePath = `./LICENSE`
	const bannerPath  = `docs/banner.png`

	return `<!-- File autogenerated by .dovenv/readme.js. Please do not edit HERE cause it will be overwritten -->
<!--\n${await getMark( pkg )}\n-->

# ${pkg.extra.productName.toUpperCase()} - MacOS App Trial Extender

[![HEADER](${bannerPath})](${pkg.repository.url})

${createMdLinks( [
	{
		name   : 'License',
		URL    : licensePath,
		imgURL : createBadgeURL( {
			color : 'green',
			style : 'for-the-badge',
			name  : 'License',
			path  : `github/license/${pkg.extra.repoPath}`,
		} ),
	},
	{
		name   : 'Github Releases',
		URL    : pkg.repository.url,
		imgURL : createBadgeURL( {
			color : 'blue',
			style : 'for-the-badge',
			name  : 'Github Releases',
			path  : `github/package-json/v/${pkg.extra.repoPath}`,
		} ),
	},
] )}

${pkg.description}

> This application is for **development** purposes only.

## Download

${createMdLinks( [
	createMdLink( {
		name : 'Macos Universal',
		url  : pkg.extra.downloadUrl.macosUniversal,
	} ),
	createMdLink( {
		name : 'Macos Intel',
		url  : pkg.extra.downloadUrl.macosIntel,
	} ),
	createMdLink( {
		name : 'Macos Silicon',
		url  : pkg.extra.downloadUrl.macosSilicon,
	} ),

] )}

> [!CAUTION]
> Currently the app for Silicon is damaged, so it is advisable to install the app for macOS universal app

### All releases

${createMdLinks( [
	createMdLink( {
		name : 'All releases',
		url  : joinUrl( pkg.repository.url, 'releases' ),
	} ),
] )}

## 👨‍💻 Development

You can contribute via **_Github_**.

${createMdLinks( [
	createMdLink( {
		name  : 'Issues',
		url   : pkg.bugs.url,
		color : 'gray',
	} ),
	createMdLink( {
		name  : 'Issues',
		url   : pkg.bugs.url,
		color : 'gray',
	} ),
] )}

## ☕ Donate

Help us to develop more interesting things.

${createMdLinks( [
	createMdLink( {
		name  : 'Donate',
		url   : pkg.funding.url,
		color : 'gray',
	} ),
] )}

## 📜 License

This software is licensed with **[${pkg.license}](${licensePath})**.

${createMdLinks( [
	createMdLink( {
		name  : 'Read more',
		url   : licensePath,
		color : 'gray',
	} ),
] )}

## 🐦 About us

_PigeonPosse_ is a ✨ **code development collective** ✨ focused on creating practical and interesting tools that help developers and users enjoy a more agile and comfortable experience. Our projects cover various programming sectors and we do not have a thematic limitation in terms of projects.

${createMdLinks( [
	createMdLink( {
		name  : 'Read more',
		url   : pkg.extra.collective.url,
		color : 'gray',
	} ),
] )}

### Collaborators

|                                                                                    | Name        | Role         | GitHub                                         |
| ---------------------------------------------------------------------------------- | ----------- | ------------ | ---------------------------------------------- |
| <img src="${pkg.author.url}.png?size=72" alt="${pkg.author.name}" style="border-radius:100%"/> | ${pkg.author.name} |   Author & Development   | [@${pkg.author.name}](${pkg.author.url}) |
${createTableRow( 'YinMo19', 'Code Contributor' )}
${createTableRow( pkg.extra.collective.name, 'Collective' )}

</br>

<p align="center">

${createMdLinks( [
	createMdLink( {
		name  : 'Web',
		url   : pkg.extra.collective.web,
		color : 'grey',
	} ),
	createMdLink( {
		name  : 'About Us',
		url   : pkg.extra.collective.about,
		color : 'grey',
	} ),
	createMdLink( {
		name  : 'Donate',
		url   : pkg.funding.url,
		color : 'pink',
	} ),
	createMdLink( {
		name  : 'Github',
		url   : pkg.extra.collective.gh,
		logo  : 'github',
		color : 'black',
	} ),
	createMdLink( {
		name  : 'Twitter',
		url   : pkg.extra.collective.social.twitter,
		logo  : 'x',
		color : 'black',
	} ),
	createMdLink( {
		name  : 'Instagram',
		url   : pkg.extra.collective.social.instagram,
		logo  : 'instagram',
		color : 'black',
	} ),
	createMdLink( {
		name  : 'Medium',
		url   : pkg.extra.collective.social.medium,
		logo  : 'medium',
		color : 'black',
	} ),
] )}

</p>
`

}

export default defineConfig( { custom : { readme : {
	desc : 'Create dynamic readme',
	fn   : async () => {

		try {

			const readme = await setReadme( pkg )
			await writeFile( 'README.md', readme )

		}
		catch ( err ) {

			console.error( err )

		}

	},
} } } )
